### ISSUE TITLE
Link to "Contributing (inbound-outbound)" in README.md table of contents does not work. 

### ISSUE THREAD

**Issue by tysonfromearth** [decryptofy/scarr#10]
Steps to reproduce:
1. Navigate to https://github.com/decryptofy/scarr
2. Scroll down to Table of Contents
3. Click "Contributing (inbound = outbound)"
4. Expected behavior: URL is updated in browser and browser navigates to contribution section of README.md
    Actual behavior: URL is updated but navigation does not occur

Before click:
![image](https://github.com/decryptofy/scarr/assets/40677874/90cdb21d-ed0d-4ea0-b4be-66c0154929b8)

After click:
![image](https://github.com/decryptofy/scarr/assets/40677874/473883c9-aaaa-4476-bcf5-5efd6c0ca669)

OS: Windows 11
Browser: Chrome Version 125.0.6422.76 (Official Build) (64-bit)

**Comment by decryptofy** [comment]
This is now fixed. Thanks
