### ISSUE TITLE
Typos and Grammar in ARCHITECTURE.md

### ISSUE THREAD

**Issue by bartokay** [decryptofy/scarr#12]
I found a few typos and grammatical improvements that could be made in this file.

Ex:
Possessive singular of class:
https://github.com/decryptofy/scarr/blob/c82e8ae2b0503cefe8d787f4c36f9be58dab1ad0/ARCHITECTURE.md?plain=1#L58

Sentence structure and missing commas:
https://github.com/decryptofy/scarr/blob/c82e8ae2b0503cefe8d787f4c36f9be58dab1ad0/ARCHITECTURE.md?plain=1#L70

Is it alright if I make these changes and fix a couple other minor typos?

**Comment by boslandj** [comment]
Yes! Please put in a PR with your fixes and I would be happy to approve it. Thank you for contributing.

**Comment by bartokay** [comment]
Hi @boslandj, thank you! I can open the pull request today. But before I do, should I still reference this issue even though it's been closed as completed already?
