### ISSUE TITLE
Low Test Coverage

### ISSUE THREAD

**Issue by nicklaustrup** [decryptofy/scarr#20]
Hello, 

I am a student at Oregon State University and taking the Open Source Software course. For an assignment, we have been instructed to run tests on a software repo to look for opportunities to contribute. 

I chose to run a test coverage report for SCARR and found that the overall test coverage percentage was 54% which may be lower than the maintainers' desired coverage. 

![image](https://github.com/user-attachments/assets/f127a1b8-994d-40af-9c50-3079c8153dde)

Based on my limited understanding of SCARR, it seems the 'Engine' classes present the greatest opportunity to increase impactful test coverage.

To generate this report, I used coverage which operates under the Apache 2.0 license:

https://github.com/nedbat/coveragepy?tab=Apache-2.0-1-ov-file#readme

**Comment by decryptofy** [comment]
Hi Nicholas,

Thank you for your interest in improving SCARR. Let me briefly comment here:

Apache 2 is perfectly fine and compatible with MPL2 of this project.

I'm not familiar with this coverage test tool. Just some simple observations here:

- If you look at its [documentation](https://coverage.readthedocs.io/en/7.6.7/), you will see that for testing coverage, it implies a given set of input parameters, i.e., that is not the case when running this over the project files themselves without any inputs
- "Coverage doesn’t distinguish between tests and the code being tested", i.e., special attentions needs to be paid, as this project currently does not have any (unit) tests -- a great area of future improvement.

Perhaps you can comment on how to specifically address this issue for one of the specific files (such as: sbox_weight.py).

**Comment by decryptofy** [comment]
While we don't have tests (obviously, an issue), I don't know how to act upon this further. Closed.
