### ISSUE TITLE
Elaboration of CONTRIBUTING.md and Contributor Guide

### ISSUE THREAD

**Issue by longtr28** [decryptofy/scarr#9]
Hello! The purpose of this issue is to request expansion of the documentation in the contributor’s guide to formalize it. The “Contributing Process” is clearly stated as TBD, but it would be helpful to potentially add more specificity to the contributor’s guide, perhaps via a more extensive description of how to contribute to each of the following: development, documentation, feature requests, patches, bug reporting, and user support. It may be even more helpful to include links to pull requests and successful prior instances of each form of contribution for future contributors to look to for guidance. Below is one possible way to begin adding more detail to the Contributor’s Guide:
<img width="468" alt="Contributor Guide" src="https://github.com/decryptofy/scarr/assets/97005479/c34583b5-2788-4a85-bf00-682d7f5ede23">

Another idea to improve this documentation through the same lens is to include a “Steps to a Successful Developer Contribution” section. I have seen some large and successful open-source projects include one as part of their documentation for contributors. The idea below could potentially be a starting point to introduce this:
<img width="468" alt="Contributing Process" src="https://github.com/decryptofy/scarr/assets/97005479/54a5e3d5-62f3-4dc7-80bc-1de4311acbe3">

I plan to follow up on this suggestion in the coming weeks with pull requests that will outline specific, actionable, and more thorough changes for others to review and refine.

**Comment by decryptofy** [comment]
Your efforts are appreciated. For the contribution process, we should also add:

- For newly added Python source code files, to include the Mozilla Public License 2.0 (no copyleft exception) header
- For newly included Python packages, to run liccheck -s license_check.ini to make sure that only license-compatible projects are included (next step: include that as a GitHub action)
- For new contributors that add/modify/extend source code files under the MPL 2.0 license, to include themselves in the list of contributors in the README.md (i.e., the term contribution and contributor follow the MPL 2.0 license definitions)

I'm looking forward to your contribution!
